name: Deployment pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches: [main]
  #   types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push'}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: npm install && cd client && npm install
      - name: lint
        run: npm run eslint
      - name: npm build
        run: npm run build:ui
      #     - name: npm test
      #       run: npm run test
      #     - name: e2e tests
      #       uses: cypress-io/github-action@v4
      #       with:
      #         build: npm run build
      #         start: npm run start-prod
      #         wait-on: http://localhost:5000
      - name: heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phonebook-cicd123"
          heroku_email: "sunsetsin1.sy@gmail.com"
          healthcheck: "https://phonebook-cicd123.herokuapp.com//health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   if: ${{ github.event_name == 'push'}}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: '0'
  #     - name: Bump version and push tag
  #       uses: anothrNick/github-tag-action@1.36.0
  #       if: ${{!contains(env.JOIN_COMMIT_MESSAGES, '#skip') }}

  #       env:
  #         JOIN_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         default: patch
  #         WITH_V: true
  #         DEFAULT_BUMP: patch
  #     - name: Discord Webhook Notify
  #       uses: rjstone/discord-webhook-notify@v1.0.4
  #       if: success()
  #       with:
  #         severity: info
  #         text: New version of Pokedex app deployed
  #         description: to https://pokedexsand.herokuapp.com by sandhya
  #         webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
  #     - name: Test Failure
  #       uses: rjstone/discord-webhook-notify@v1.0.4
  #       if: failure()
  #       with:

  #         severity: error
  #         details: test failed
  #         webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
